caching: true

completion_kwargs:
  model: llama3-70b-8192
  temperature: 0.5
  max_tokens: 500
  stop: ['</subquestions>']

trims:
  - name: 'SEARCH_RESULTS'
    trim_type: 'END'
    min_length: 3000
    max_length: 4000

  - name: 'SUBQUESTION_TREE'
    trim_type: 'END'
    min_length: 100
    max_length: 1000

  - name: 'ORIGINAL_QUESTION'
    trim_type: 'END'
    min_length: 100
    max_length: 500

  - name: 'CURRENT_SUBQUESTION'
    trim_type: 'END'
    min_length: 100
    max_length: 500