model_list:
  - model_name: gpt-4o-2024-08-06
    litellm_params:
      model: gpt-4o-2024-08-06
      api_key: "os.environ/OPENAI_API_KEY"
      rpm: 100
  - model_name: gpt-4o-2024-05-13
    litellm_params:
      model: gpt-4o-2024-05-13
      api_key: "os.environ/OPENAI_API_KEY"
      rpm: 10
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: "os.environ/OPENAI_API_KEY"
      rpm: 100
      
litellm_settings:
  num_retries: 3 # retry call 3 times on each model_name (e.g. zephyr-beta)
  request_timeout: 100 # raise Timeout error if call takes longer than 10s. Sets litellm.request_timeout 
  fallbacks: [{"llama3-70b-8192": ["claude-3-haiku-20240307"]}] # fallback to if call fails num_retries 
  allowed_fails: 3 # cooldown model if it fails > 1 call in a minute. 
  success_callback: ["langfuse"]
  redact_user_api_key_info: true
  cache: True
  cache_params:
    type: redis
    host: localhost
    port: 6379
    password: "" # leave empty if no password set
    ttl: 25920000  # 300 days in seconds (300 * 24 * 60 * 60)

general_settings: 
  master_key: "sk-ade-myreallystrongmasterkeyhahah4359rt8guifhj" # [OPTIONAL] Only use this if you to require all calls to contain this key (Authorization: Bearer sk-1234)
  # database_url: "postgresql://postgres.xflzlnqtoarcfelrdbvv:nessyd-mesTef-kesvi2@aws-0-us-east-1.pooler.supabase.com:6543/postgres"