caching: true

completion_kwargs:
  # model: llama3-70b-8192
  # model: gpt-4o
  # model: claude-3-haiku-20240307
  model: gpt-4o-mini
  temperature: 0.1
  max_tokens: 4000


trims:
  - name: 'SEARCH_RESULTS'
    trim_type: 'END'
    min_length: 10000
    max_length: 40000


  - name: 'PREVIOUS_QUERIES_AND_STATEMENTS'
    trim_type: 'START'
    min_length: 10000
    max_length: 40000

  - name: 'MAIN_QUESTION'
    trim_type: 'END'
    min_length: 10000
    max_length: 20000

  - name: 'QUERY'
    trim_type: 'END'
    min_length: 10000
    max_length: 20000