caching: true

completion_kwargs:
  # model: gpt-4o-mini
  model: gpt-4o-2024-08-06
  temperature: 0.3
  max_tokens: 2000


trims:
  - name: 'QUOTES'
    trim_type: 'END'
    min_length: 90000
    max_length: 100000